function(print_build_summary)
    message("\n[ pgModeler build paths ]")
    message("* PGM_PREFIX        = ${PGM_PREFIX}")
    message("* PGM_BINDIR        = ${PGM_BINDIR}")
    message("* PGM_PRIVATEBINDIR = ${PGM_PRIVATEBINDIR}")
    message("* PGM_PRIVATELIBDIR = ${PGM_PRIVATELIBDIR} ")
    message("* PGM_PLUGINSDIR    = ${PGM_PLUGINSDIR}")
    message("* PGM_SHAREDIR      = ${PGM_SHAREDIR}")
    message("* PGM_CONFDIR       = ${PGM_CONFDIR}")
    message("* PGM_DOCDIR        = ${PGM_DOCDIR}")
    message("* PGM_LANGDIR       = ${PGM_LANGDIR}")
    message("* PGM_SAMPLESDIR    = ${PGM_SAMPLESDIR}")
    message("* PGM_SCHEMASDIR    = ${PGM_SCHEMASDIR}\n")

    message("[ Dependencies ]")
    message("* C compiler         = ${CMAKE_C_COMPILER}")
    message("* C++ compiler       = ${CMAKE_CXX_COMPILER}")
    message("* PostgreSQL headers = ${PGSQL_INC}")
    message("* PostgreSQL library = ${PGSQL_LIBS}")
    message("* LibXml2 headers    = ${XML2_INC}")
    message("* LibXml2 library    = ${XML2_LIBS}")
    message("* Clang-tidy binary  = ${CLANG_TIDY_EXE}")

    message("\n[ Extra build options / Info ]")
    message("* NO_CHECK_CURR_VER  = ${NO_CHECK_CURR_VER}")
    message("* SNAPSHOT_BUILD     = ${SNAPSHOT_BUILD}")
    message("* APPIMAGE_BUILD     = ${APPIMAGE_BUILD}")
    message("* DEMO_VERSION       = ${DEMO_VERSION}")
    message("* PLUS_VERSION       = ${PLUS_VERSION}")
    message("* NO_UPDATE_CHECK    = ${NO_UPDATE_CHECK}")
    message("* BUILD_PLUGINS      = ${BUILD_PLUGINS}")
    message("* BUILD_PRIV_PLUGINS = ${BUILD_PRIV_PLUGINS}")
    message("* BUILD_TESTS        = ${BUILD_TESTS}")
    message("* USE_CLANG_TIDY     = ${USE_CLANG_TIDY}")
	message("* CMAKE_BUILD_TYPE   = ${CMAKE_BUILD_TYPE}\n")
    
    message("* To change a variable's value run cmake again from source root and setting the new value, e.g.:")
    message("  > cmake -S . -DPGM_PREFIX=/usr/local -B ./cmake-build --fresh \n")
    message("* To proceed with build process run: ")
    message("  > cmake --build ./cmake-build --target all\n")
    message("* To install the compiled files run:")
    message("  > cmake --install ./cmake-build\n")
endfunction()
